logging:
  level: INFO
  loggers:
    com.redislabs.university: DEBUG
defaultName: "RediSolar"
redis:
  host: 83.101.151.10
  port: 6379
  password:
server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 8081
  adminConnectors:
    - type: http
      port: 8084

